server:
  port: ${PORT:8080}

spring:
  application:
    name: user-service
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}

aws:
  region: ${AWS_REGION:eu-central-1}
  dynamodb:
    users:
      table-name: ${DYNAMODB_USERS_TABLE:NexaUsers}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
