server:
  port: ${PORT:8080}

spring:
  application:
    name: user-service
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_hPsBH1Y7y

aws:
  region: eu-central-1
  dynamodb:
    users:
      table-name: NexaUsers

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true