server:
  port: 8081

spring:
  application:
    name: search-service
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_hPsBH1Y7y

aws:
  region: eu-central-1
  dynamodb:
    catalog:
      table-name: NexaCatalog
      sk-index: sk-index
  opensearch:
    endpoint: search-nexa-search-lvqeb42upgyez75ixzxo6utlnu.eu-central-1.es.amazonaws.com