server:
  port: ${PORT:8080}

spring:
  application:
    name: catalog-service

aws:
  region: ${AWS_REGION:eu-central-1}
  dynamodb:
    catalog:
      table-name: ${DYNAMODB_CATALOG_TABLE:NexaCatalog}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

origin:
  secret: ${ORIGIN_SECRET:}
